language: node_js
node_js:
    - '6'

cache:
    directories:
        - node_modules

branches:
    only:
        - master

notifications:
    email:
        on_success: never
        on_failure: always

before_script:
    - npm prune

script:
    - npm run test

after_success:
    - npm run semantic-release

